### ISSUE TITLE
Use consistent, file-based logging settings

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/osome-csdl-ranking-challenge#10]
# Tasks
- [X] Move `dante.osomerank.utils:get_logger` to `dante.utils:get_logger`
- [X] Use `get_logger` throughout the package (both `dante.app` and `dante.osomerank`)
- [ ] Switch to `logging.config` instead of hardcoded settings in `get_logger`

# Summary

Right now `dante.osomerank` configures the logger manually (`dante.osomerank.utils.get_logger`), while the rankers/workers in `dante.app` ~~use file-based [logging config](https://docs.python.org/3/library/logging.config.html)~~ set their own log format and level. It would be a good idea to use a consistent way to create the logger and also to switch to file-based config, which would allow for different configuration settings for development vs production. 

At least two different configurations come time mind:

## 1. Development config
 - The Package is installed as an editable install (`pip -e`)
 - All dependency groups are installed in the same virtualenv
 - Level INFO messages sent to the console
 - Level DEBUG messages sent to file in [user's logs directory](https://platformdirs.readthedocs.io/en/latest/api.html#logs-directory) with log rotation and compression (see [cookbook example](https://docs.python.org/3/howto/logging-cookbook.html#using-a-rotator-and-namer-to-customize-log-rotation-processing))
## 2. Deployment config
 - The Package is built for a particular docker image (e.g. ranker, scorer, etc.) 
 - Only the respective dependency group is installed in the virtualenv (to save space)
 - Level INFO messages sent to syslog (no rotation needed as this is handled by syslogd)
